#!/bin/bash
# Validate that service is running
HEALTH_DIR=`dirname $0`
UNIT_DIR=`dirname $HEALTH_DIR`
. $UNIT_DIR/scriptrc
set -e

# Grab any OPENSTACK_SERVICE* environment variables
openstack_service_names=`env| awk -F '=' '(/OPENSTACK_SERVICE/){print $2}'`
for service_name in $openstack_service_names
do
    service $service_name status | grep -q running
done
